/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryTictactoe.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryTictactoe (6 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLTictactoeGame;

@interface GTLQueryTictactoe : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark "gamePlay" methods
// These create a GTLQueryTictactoe object.

// Method: tictactoe.gamePlay.getCurrentGameBoard
// Fetches a GTLTictactoeGame.
+ (id)queryForGamePlayGetCurrentGameBoardWithObject:(GTLTictactoeGame *)object;

// Method: tictactoe.gamePlay.markGameAsFinished
// Fetches a GTLTictactoeScore.
+ (id)queryForGamePlayMarkGameAsFinishedWithObject:(GTLTictactoeGame *)object;

// Method: tictactoe.gamePlay.updateGameWithNewBoard
// Fetches a GTLTictactoeGame.
+ (id)queryForGamePlayUpdateGameWithNewBoardWithObject:(GTLTictactoeGame *)object;

#pragma mark -
#pragma mark "games" methods
// These create a GTLQueryTictactoe object.

// Method: tictactoe.games.list
// Fetches a GTLTictactoeGameCollection.
+ (id)queryForGamesList;

#pragma mark -
#pragma mark "matchmaking" methods
// These create a GTLQueryTictactoe object.

// Method: tictactoe.matchmaking.findOrCreateGame
// Fetches a GTLTictactoeGame.
+ (id)queryForMatchmakingFindOrCreateGame;

#pragma mark -
#pragma mark "scores" methods
// These create a GTLQueryTictactoe object.

// Method: tictactoe.scores.list
// Fetches a GTLTictactoeScoreCollection.
+ (id)queryForScoresList;

@end
