/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLTictactoeScore.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API
// Classes:
//   GTLTictactoeScore (0 custom class methods, 7 custom properties)

#import "GTLTictactoeScore.h"

#import "GTLTictactoeUser.h"

// ----------------------------------------------------------------------------
//
//   GTLTictactoeScore
//

@implementation GTLTictactoeScore
@dynamic board, date, identifier, outcome, playerTurn, user1, user2;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
