/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLTictactoe_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API

#import "GTLTictactoeGame.m"
#import "GTLTictactoeGameCollection.m"
#import "GTLTictactoeScore.m"
#import "GTLTictactoeScoreCollection.m"
#import "GTLTictactoeUser.m"

#import "GTLQueryTictactoe.m"
#import "GTLServiceTictactoe.m"
