/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLTictactoeGame.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API
// Classes:
//   GTLTictactoeGame (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLTictactoeUser;

// ----------------------------------------------------------------------------
//
//   GTLTictactoeGame
//

@interface GTLTictactoeGame : GTLObject
@property (copy) NSString *board;
@property (retain) GTLDateTime *date;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *playerTurn;  // intValue
@property (retain) GTLTictactoeUser *user1;
@property (retain) GTLTictactoeUser *user2;
@end
