/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLTictactoeScore.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API
// Classes:
//   GTLTictactoeScore (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLTictactoeUser;

// ----------------------------------------------------------------------------
//
//   GTLTictactoeScore
//

@interface GTLTictactoeScore : GTLObject
@property (copy) NSString *board;
@property (retain) GTLDateTime *date;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *outcome;
@property (retain) NSNumber *playerTurn;  // intValue
@property (retain) GTLTictactoeUser *user1;
@property (retain) GTLTictactoeUser *user2;
@end
