/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLTictactoe.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API

#import "GTLTictactoeGame.h"
#import "GTLTictactoeGameCollection.h"
#import "GTLTictactoeScore.h"
#import "GTLTictactoeScoreCollection.h"
#import "GTLTictactoeUser.h"

#import "GTLQueryTictactoe.h"
#import "GTLServiceTictactoe.h"
