/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLTictactoeGame.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Description:
//   This is an API
// Classes:
//   GTLTictactoeGame (0 custom class methods, 6 custom properties)

#import "GTLTictactoeGame.h"

#import "GTLTictactoeUser.h"

// ----------------------------------------------------------------------------
//
//   GTLTictactoeGame
//

@implementation GTLTictactoeGame
@dynamic board, date, identifier, playerTurn, user1, user2;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
